### ISSUE TITLE
tried both december 27 releases

### ISSUE THREAD

**Issue by kreezxil** [CodeCraftPlugin/EatMobMod#1]
yes there was something here, but it was inaccurate.

**Comment by kreezxil** [comment]
also this is the issue tracker I was talking about, the one on CurseForge subpar compared to github and gitlab.

**Comment by CodeCraftPlugin** [comment]
so like what is the issue
Do you want to make this the issue tracker?

**Comment by CodeCraftPlugin** [comment]
i will change the issue tracker
